import {
  UserProfile,
  Application,
  LearningTrack,
  SkillNode,
  XPTransaction,
  HardwareAsset,
  LabResource,
  LabBooking,
  Project,
  TeamRecruitmentPost,
  MonthlyChallenge,
  ClubEvent,
  HackathonOpportunity,
  CertificateRecord,
  TelemetryData,
  AuditLogItem,
  AppNotification,
} from "./types";

export const initialDemoStudent: UserProfile = {
  id: "std-001",
  name: "Hari Dharanesh SP",
  username: "hari",
  headline: "IoT & Embedded Systems Engineer",
  level: 4,
  levelTitle: "IoT Builder",
  xp: 1450,
  rollNumber: "22IOT042",
  department: "Internet of Things & Embedded Systems",
  year: "3rd Year",
  section: "A",
  collegeEmail: "hari.dharanesh@student.college.edu",
  personalEmail: "hari.iotdev@example.com",
  phone: "+91 98765 43210",
  avatarUrl: "",
  githubUrl: "https://github.com/hari-iot",
  linkedinUrl: "https://linkedin.com/in/hari-dharanesh",
  portfolioUrl: "https://iotclub.org/member/hari",
  bio: "Passionate about low-latency edge computing, FreeRTOS firmware design, and ESP32 mesh networks. Leading project CareGrid.",
  isPublic: true,
  skills: [
    { name: "Embedded Systems (C/C++)", level: "Advanced", proficiencyPercent: 80 },
    { name: "IoT Networking & MQTT", level: "Advanced", proficiencyPercent: 70 },
    { name: "Python for Edge", level: "Advanced", proficiencyPercent: 80 },
    { name: "Linux & Shell", level: "Intermediate", proficiencyPercent: 70 },
    { name: "Cybersecurity in IoT", level: "Intermediate", proficiencyPercent: 60 },
    { name: "Robotics & Actuators", level: "Intermediate", proficiencyPercent: 50 },
    { name: "PCB Design (KiCAD)", level: "Intermediate", proficiencyPercent: 65 },
    { name: "FreeRTOS", level: "Intermediate", proficiencyPercent: 75 },
  ],
  roles: ["STUDENT", "PROJECT_LEAD"],
  stats: {
    projects: 7,
    hackathons: 5,
    workshops: 14,
    certificates: 8,
    mentoringSessions: 5,
    clubContributions: 32,
  },
};

export const initialApplications: Application[] = [
  {
    id: "APP-2026-001",
    fullName: "Aravind Kumar",
    rollNumber: "24EC018",
    department: "Electronics & Communication",
    year: "1st Year",
    section: "B",
    collegeEmail: "aravind.k@student.college.edu",
    personalEmail: "aravind.dev@gmail.com",
    phone: "+91 91234 56789",
    interests: ["IoT", "Embedded Systems", "Robotics", "ESP32"],
    skills: [
      { name: "C Programming", level: "Intermediate" },
      { name: "Arduino IDE", level: "Beginner" },
      { name: "Basic Electronics", level: "Intermediate" },
    ],
    githubUrl: "https://github.com/aravind-k",
    linkedinUrl: "https://linkedin.com/in/aravind-k",
    whyJoin: "I want to build real hardware devices, master microcontrollers, and work on club hackathon teams.",
    whatToLearn: "FreeRTOS, ESP32 Wi-Fi architecture, and IoT sensor networks.",
    hoursPerWeek: "10-12 hrs",
    hackathonInterest: true,
    researchInterest: false,
    status: "ASSESSMENT",
    appliedDate: "2026-09-08",
    batch: "2026 Batch 01",
  },
  {
    id: "APP-2026-002",
    fullName: "Pooja Sundaram",
    rollNumber: "23CS104",
    department: "Computer Science & Engineering",
    year: "2nd Year",
    section: "A",
    collegeEmail: "pooja.s@student.college.edu",
    personalEmail: "pooja.sundaram@gmail.com",
    phone: "+91 98451 23456",
    interests: ["AIoT", "Computer Vision", "Edge AI", "Python"],
    skills: [
      { name: "Python", level: "Advanced" },
      { name: "OpenCV", level: "Intermediate" },
      { name: "Git / GitHub", level: "Intermediate" },
    ],
    githubUrl: "https://github.com/pooja-cv",
    linkedinUrl: "https://linkedin.com/in/pooja-s",
    whyJoin: "Excited to combine machine learning algorithms with physical cameras and Raspberry Pi accelerators.",
    whatToLearn: "YOLO on embedded edge hardware and ROS 2 integration.",
    hoursPerWeek: "12-15 hrs",
    hackathonInterest: true,
    researchInterest: true,
    status: "INTERVIEW",
    appliedDate: "2026-09-05",
    batch: "2026 Batch 01",
  },
  {
    id: "APP-2026-003",
    fullName: "Karthik Raja",
    rollNumber: "24ME045",
    department: "Mechanical Engineering",
    year: "1st Year",
    section: "C",
    collegeEmail: "karthik.r@student.college.edu",
    personalEmail: "karthik.raja@outlook.com",
    phone: "+91 97890 12345",
    interests: ["Robotics", "CAD", "Automation", "Drone Technology"],
    skills: [
      { name: "SolidWorks / CAD", level: "Intermediate" },
      { name: "Arduino", level: "Beginner" },
    ],
    githubUrl: "https://github.com/karthik-cad",
    linkedinUrl: "https://linkedin.com/in/karthik-raja",
    whyJoin: "I want to design robotic chassis, test motor controllers, and 3D print functional mechanisms.",
    whatToLearn: "Motor kinematics, servo control, and autonomous rovers.",
    hoursPerWeek: "8-10 hrs",
    hackathonInterest: true,
    researchInterest: false,
    status: "PRACTICAL_TASK",
    appliedDate: "2026-09-07",
    batch: "2026 Batch 01",
  },
  {
    id: "APP-2026-004",
    fullName: "Sneha Reddy",
    rollNumber: "23IT077",
    department: "Information Technology",
    year: "2nd Year",
    section: "B",
    collegeEmail: "sneha.r@student.college.edu",
    personalEmail: "sneha.reddy@gmail.com",
    phone: "+91 94455 66778",
    interests: ["Cybersecurity", "Cloud IoT", "MQTT", "HTTP APIs"],
    skills: [
      { name: "Linux", level: "Intermediate" },
      { name: "Networking", level: "Intermediate" },
      { name: "Python", level: "Intermediate" },
    ],
    githubUrl: "https://github.com/sneha-sec",
    linkedinUrl: "https://linkedin.com/in/sneha-reddy",
    whyJoin: "IoT device security is often overlooked; I want to harden club infrastructure and implement encrypted MQTT brokers.",
    whatToLearn: "TLS certificates on ESP32, secure boot, and hardware penetration testing.",
    hoursPerWeek: "10 hrs",
    hackathonInterest: false,
    researchInterest: true,
    status: "UNDER_REVIEW",
    appliedDate: "2026-09-10",
    batch: "2026 Batch 01",
  },
  {
    id: "APP-2026-005",
    fullName: "Vikas Narayanan",
    rollNumber: "24EE029",
    department: "Electrical & Electronics",
    year: "1st Year",
    section: "A",
    collegeEmail: "vikas.n@student.college.edu",
    personalEmail: "vikas.n@gmail.com",
    phone: "+91 93821 09876",
    interests: ["Electronics", "PCB Design", "Sensors", "ESP32"],
    skills: [
      { name: "Circuit Analysis", level: "Intermediate" },
      { name: "KiCAD", level: "Beginner" },
    ],
    githubUrl: "https://github.com/vikas-circuits",
    linkedinUrl: "https://linkedin.com/in/vikas-n",
    whyJoin: "Passionate about hardware power optimization and designing custom circuit boards.",
    whatToLearn: "SMD soldering, battery management systems, and LoRa transceiver nodes.",
    hoursPerWeek: "12 hrs",
    hackathonInterest: true,
    researchInterest: false,
    status: "SUBMITTED",
    appliedDate: "2026-09-11",
    batch: "2026 Batch 01",
  },
];

export const initialLearningTracks: LearningTrack[] = [
  {
    id: "trk-01",
    slug: "iot-foundations",
    title: "Track 1 – IoT Foundations",
    description: "Electronics fundamentals, sensor interfacing, Arduino, ESP32 architecture, and communication protocols.",
    icon: "Cpu",
    color: "#10b981",
    progressPercent: 100,
    modulesCount: 5,
    completedModulesCount: 5,
    modules: [
      {
        id: "mod-101",
        trackId: "trk-01",
        title: "Electronics Basics & Breadboarding",
        overview: "Ohm's law, pull-up/pull-down resistors, digital vs analog signals, voltage regulation, and decoupling capacitors.",
        level: "Beginner",
        estimatedHours: 4,
        badge: "Electronics Fundamentals",
        isUnlocked: true,
        isCompleted: true,
        lessons: [
          {
            id: "les-101",
            title: "Ohm's Law & Circuit Protection",
            duration: "45 mins",
            conceptSummary: "Voltage (V) = Current (I) * Resistance (R). Understanding how to calculate current-limiting resistors for LEDs and protecting microcontroller GPIOs from overcurrent.",
            circuitDiagramNote: "LED with 220Ω resistor connected in series between ESP32 Pin GPIO2 and GND.",
            codeSnippet: "void setup() {\n  pinMode(2, OUTPUT);\n}\nvoid loop() {\n  digitalWrite(2, HIGH);\n  delay(500);\n  digitalWrite(2, LOW);\n  delay(500);\n}",
          },
        ],
      },
      {
        id: "mod-102",
        trackId: "trk-01",
        title: "Sensors & Actuators Interfacing",
        overview: "Analog sensors (LDR, Thermistors, Potentiometers) and digital sensors (DHT22, Ultrasonic HC-SR04, PIR).",
        level: "Beginner",
        estimatedHours: 6,
        badge: "Sensor Specialist",
        isUnlocked: true,
        isCompleted: true,
        lessons: [
          {
            id: "les-102",
            title: "ADC Resolution & Analog Sampling",
            duration: "50 mins",
            conceptSummary: "ESP32 provides 12-bit ADC (0-4095 range) on ADC1 and ADC2 pins. Learn calibration and attenuation settings.",
          },
        ],
      },
    ],
  },
  {
    id: "trk-02",
    slug: "embedded-systems",
    title: "Track 2 – Embedded Systems",
    description: "Bare-metal C/C++, GPIO registers, Interrupt Service Routines (ISR), ADC, PWM timers, I2C/SPI buses, and FreeRTOS.",
    icon: "Layers",
    color: "#06b6d4",
    progressPercent: 67,
    modulesCount: 6,
    completedModulesCount: 4,
    modules: [
      {
        id: "mod-201",
        trackId: "trk-02",
        title: "ESP32 Architecture & FreeRTOS",
        overview: "Dual-core Xtensa LX7 processor, FreeRTOS tasks, task priorities, queues, mutexes, and semaphores.",
        level: "Intermediate",
        estimatedHours: 8,
        badge: "FreeRTOS Engineer",
        isUnlocked: true,
        isCompleted: true,
        lessons: [
          {
            id: "les-201",
            title: "Creating Independent FreeRTOS Tasks",
            duration: "60 mins",
            conceptSummary: "xTaskCreatePinnedToCore pinpoints tasks to Core 0 (Wi-Fi/Network stack) or Core 1 (Sensor sampling/Compute).",
            codeSnippet: "// FreeRTOS Task Pinning Example\nxTaskCreatePinnedToCore(\n  SensorTask,\n  \"SensorTask\",\n  4096,\n  NULL,\n  1,\n  &xSensorTaskHandle,\n  0 // Core 0\n);",
          },
        ],
      },
      {
        id: "mod-202",
        trackId: "trk-02",
        title: "ESP32 Practical MQTT Automation",
        overview: "Building resilient MQTT publisher/subscriber nodes with automatic Wi-Fi reconnect and keep-alive heartbeats.",
        level: "Intermediate",
        estimatedHours: 10,
        badge: "ESP32 Developer",
        isUnlocked: true,
        isCompleted: false,
        lessons: [
          {
            id: "les-202",
            title: "MQTT QoS Levels & Last Will Testament",
            duration: "75 mins",
            conceptSummary: "QoS 0 (At most once), QoS 1 (At least once), QoS 2 (Exactly once). Implementing LWT for instantaneous dead-node detection.",
          },
        ],
        assignment: {
          id: "asg-202",
          moduleId: "mod-202",
          title: "ESP32 Automatic Lighting & MQTT Telemetry",
          description: "Build an ESP32 firmware that reads ambient light via BH1750 (I2C) or ADC, automatically controls relay outputs, publishes state telemetry via MQTT every 5 seconds, and subscribes to remote override commands.",
          submissionRequirements: [
            "Clean C++ / Arduino / ESP-IDF source code in GitHub repo",
            "Circuit diagram / schematic PNG or PDF",
            "Demonstration video (Loom/YouTube or MP4 link)",
            "README.md with setup instructions and topic taxonomy",
          ],
          maxXP: 100,
          badgeReward: "ESP32 Developer",
          dueDate: "2026-09-20",
          rubrics: [
            { name: "Circuit Design & Wiring Safety", maxScore: 20, description: "Correct pull-ups, proper voltage levels, relay flyback diode protection" },
            { name: "Code Quality & FreeRTOS Structure", maxScore: 20, description: "Non-blocking delays, proper state machines, clean naming" },
            { name: "MQTT Implementation & Topics", maxScore: 25, description: "Structured JSON payloads, retain flags, Last Will Testament implementation" },
            { name: "Error Handling & Reconnection", maxScore: 15, description: "Graceful reconnection when Wi-Fi or broker drops" },
            { name: "Documentation & README", maxScore: 10, description: "Pinout table, dependencies, setup instructions" },
            { name: "Working Live Demonstration", maxScore: 10, description: "Clear video demonstration showing sensor response and broker terminal" },
          ],
        },
      },
    ],
  },
  {
    id: "trk-03",
    slug: "raspberry-pi-linux",
    title: "Track 3 – Raspberry Pi & Linux",
    description: "Linux shell scripting, GPIO pins, systemd background services, Docker containers, and edge IoT gateways.",
    icon: "Terminal",
    color: "#8b5cf6",
    progressPercent: 40,
    modulesCount: 5,
    completedModulesCount: 2,
    modules: [],
  },
  {
    id: "trk-04",
    slug: "iot-networking",
    title: "Track 4 – IoT Networking",
    description: "Wi-Fi, Bluetooth Low Energy (BLE), MQTT, HTTP/REST, WebSockets, LoRa, and TCP/IP network layers.",
    icon: "Wifi",
    color: "#3b82f6",
    progressPercent: 70,
    modulesCount: 6,
    completedModulesCount: 4,
    modules: [],
  },
  {
    id: "trk-05",
    slug: "iot-security",
    title: "Track 5 – IoT Security",
    description: "Hardware secure boot, flash encryption, TLS/MQTTS encryption, secure API tokens, and firmware hardening.",
    icon: "ShieldAlert",
    color: "#f43f5e",
    progressPercent: 20,
    modulesCount: 5,
    completedModulesCount: 1,
    modules: [],
  },
  {
    id: "trk-06",
    slug: "aiot",
    title: "Track 6 – AIoT & Edge AI",
    description: "Embedded machine learning, OpenCV vision pipelines, YOLO object detection on Raspberry Pi, and hardware accelerators.",
    icon: "Eye",
    color: "#f59e0b",
    progressPercent: 30,
    modulesCount: 6,
    completedModulesCount: 2,
    modules: [],
  },
  {
    id: "trk-07",
    slug: "robotics",
    title: "Track 7 – Autonomous Robotics",
    description: "DC & Stepper motor drivers, PID control loops, ROS 2 basics, LiDAR navigation, and robotic kinematics.",
    icon: "Bot",
    color: "#10b981",
    progressPercent: 50,
    modulesCount: 6,
    completedModulesCount: 3,
    modules: [],
  },
  {
    id: "trk-08",
    slug: "cloud-iot",
    title: "Track 8 – Cloud IoT",
    description: "Time-series databases (PostgreSQL/TimescaleDB), MQTT brokers, cloud ingest pipelines, and Grafana telemetry dashboards.",
    icon: "Cloud",
    color: "#06b6d4",
    progressPercent: 25,
    modulesCount: 5,
    completedModulesCount: 1,
    modules: [],
  },
];

export const initialSkillNodes: SkillNode[] = [
  {
    id: "sk-01",
    name: "Electronics Basics",
    category: "Foundations",
    status: "COMPLETED",
    prerequisites: [],
    xpReward: 50,
    description: "Ohm's Law, resistors, capacitors, LEDs, breadboarding, and multimeter usage.",
    icon: "Zap",
    x: 100,
    y: 100,
  },
  {
    id: "sk-02",
    name: "Arduino & Microcontrollers",
    category: "Hardware",
    status: "COMPLETED",
    prerequisites: ["sk-01"],
    xpReward: 75,
    description: "Digital I/O, Analog ADC, PWM motor control, serial monitoring, and external libraries.",
    icon: "Cpu",
    x: 250,
    y: 100,
  },
  {
    id: "sk-03",
    name: "ESP32 & Wi-Fi Stack",
    category: "Hardware",
    status: "COMPLETED",
    prerequisites: ["sk-02"],
    xpReward: 100,
    description: "Dual-core Xtensa, Wi-Fi Station & Access Point modes, Non-Volatile Storage (NVS).",
    icon: "Wifi",
    x: 400,
    y: 100,
  },
  {
    id: "sk-04",
    name: "Bus Protocols (I2C / SPI / UART)",
    category: "Protocols",
    status: "COMPLETED",
    prerequisites: ["sk-03"],
    xpReward: 100,
    description: "Clock signals, SDA/SCL lines, device addresses, SPI chip-select, and hardware interrupts.",
    icon: "Layers",
    x: 550,
    y: 50,
  },
  {
    id: "sk-05",
    name: "MQTT & Publish/Subscribe",
    category: "Protocols",
    status: "COMPLETED",
    prerequisites: ["sk-03"],
    xpReward: 120,
    description: "Lightweight telemetry, broker architecture, QoS levels, retain flags, and JSON payloads.",
    icon: "Radio",
    x: 550,
    y: 150,
  },
  {
    id: "sk-06",
    name: "FreeRTOS Kernel",
    category: "Edge & Linux",
    status: "IN_PROGRESS",
    prerequisites: ["sk-04", "sk-05"],
    xpReward: 150,
    description: "Preemptive multitasking, task priorities, queues, mutexes, and watchdog timers on ESP32.",
    icon: "Activity",
    x: 700,
    y: 100,
  },
  {
    id: "sk-07",
    name: "Raspberry Pi & Linux",
    category: "Edge & Linux",
    status: "AVAILABLE",
    prerequisites: ["sk-05"],
    xpReward: 120,
    description: "Linux headless operations, SSH, systemd services, Python GPIO, and local Mosquitto broker.",
    icon: "Terminal",
    x: 700,
    y: 200,
  },
  {
    id: "sk-08",
    name: "Edge AI & Computer Vision",
    category: "AI & Robotics",
    status: "LOCKED",
    prerequisites: ["sk-06", "sk-07"],
    xpReward: 200,
    description: "OpenCV image processing, TensorFlow Lite on Microcontrollers, YOLO Tiny edge inference.",
    icon: "Eye",
    x: 850,
    y: 150,
  },
  {
    id: "sk-09",
    name: "IoT Cloud & Dashboards",
    category: "Cloud",
    status: "AVAILABLE",
    prerequisites: ["sk-05"],
    xpReward: 150,
    description: "PostgreSQL telemetry storage, REST APIs, WebSockets, and real-time visualization dashboards.",
    icon: "Cloud",
    x: 700,
    y: 0,
  },
];

export const initialXPTransactions: XPTransaction[] = [
  { id: "xp-01", userId: "std-001", amount: 50, reason: "Completed Electronics Basics Module", category: "ASSIGNMENT", timestamp: "2026-08-15" },
  { id: "xp-02", userId: "std-001", amount: 100, reason: "Completed Arduino Sensory Practical", category: "ASSIGNMENT", timestamp: "2026-08-20" },
  { id: "xp-03", userId: "std-001", amount: 200, reason: "Mini Project: ESP32 Environmental Station", category: "MINI_PROJECT", timestamp: "2026-08-28" },
  { id: "xp-04", userId: "std-001", amount: 30, reason: "Attended FreeRTOS Hands-On Workshop", category: "WORKSHOP", timestamp: "2026-09-02" },
  { id: "xp-05", userId: "std-001", amount: 500, reason: "Hackathon Finalist: Smart India Hackathon (CareGrid)", category: "HACKATHON", timestamp: "2026-09-06" },
  { id: "xp-06", userId: "std-001", amount: 50, reason: "GitHub Contribution to Club Firmware Core", category: "COMMUNITY", timestamp: "2026-09-09" },
  { id: "xp-07", userId: "std-001", amount: 500, reason: "Milestone: CareGrid Hardware Architecture Approved", category: "PROJECT", timestamp: "2026-09-11" },
  { id: "xp-08", userId: "std-001", amount: 20, reason: "Mentored 1st Year Students on I2C Debugging", category: "MENTORING", timestamp: "2026-09-12" },
];

export const initialProjects: Project[] = [
  {
    id: "prj-001",
    title: "ADYA CareGrid",
    tagline: "Edge-AI Smart Hospital Automation & Patient-Safety Platform",
    theme: "MEDTECH / BIOTECH / HEALTHTECH",
    brief: "ADYA CareGrid is an Edge-AI based smart hospital automation and patient-safety platform that integrates smart bed monitoring, IV-level tracking, fall/emergency detection, nurse-call prioritization, environmental monitoring, and automated alert escalation into a single offline-first hospital network.",
    description: "ADYA CareGrid is an Edge-AI based smart hospital automation and patient-safety platform that integrates smart bed monitoring, IV-level tracking, fall/emergency detection, nurse-call prioritization, environmental monitoring, and automated alert escalation into a single offline-first hospital network.",
    aiToolDisclosure: "GitHub Copilot for FreeRTOS task scheduling and C++ sensor drivers; ChatGPT-4o for OpenAPI REST contract generation.",
    isLocked: true,
    lifecycle: "PROTOTYPE",
    leadName: "Hari Dharanesh S P",
    leadId: "std-001",
    members: [
      { name: "AKSHITHA B", role: "AI Model & Vision Analysis", email: "akshithabela20@gmail.com", githubHandle: "Akshitha-2007", commits: 2 },
      { name: "RASIA JAEL R", role: "Nurse Dashboard & UI Lead", email: "rasiajael05@gmail.com", githubHandle: "Rasiajael85", commits: 6 },
      { name: "LEKHA S", role: "Sensor Firmware & Calibration", email: "lekha2008@gmail.com", githubHandle: "lekha-1103", commits: 1 },
      { name: "HARI DHARANESH S P", role: "Team Lead & Edge-AI Firmware", email: "haridharanesh.sp@gmail.com", githubHandle: "haridharanesh-official", commits: 36, isLead: true },
      { name: "BALAJI M M", role: "Gateway Broker & Hardware Interfacing", email: "balajimm5139@gmail.com", githubHandle: "balaji-siet", commits: 9 },
      { name: "PRITHIC P", role: "IoT Cloud & Alert Routing", email: "prithicprithic2000@gmail.com", githubHandle: "github-username", commits: 0 },
    ],
    facultyMentor: "Faculty Mentor",
    techStack: ["ESP32-S3", "Raspberry Pi 5", "FreeRTOS", "MQTT (TLS 1.3)", "Edge-AI", "TimescaleDB", "React"],
    progressPercent: 88,
    githubUrl: "https://github.com/haridharanesh-official/CareGrid",
    defaultBranch: "main",
    totalCommits: 54,
    openIssues: 0,
    sourceAuditStatus: "Verified ✓",
    languageBreakdown: [
      { name: "Python", percentage: 51.8, color: "#3b82f6" },
      { name: "JavaScript", percentage: 41.0, color: "#eab308" },
      { name: "TypeScript", percentage: 3.4, color: "#0284c7" },
      { name: "C++", percentage: 3.2, color: "#ec4899" },
      { name: "TeX", percentage: 0.4, color: "#8b5cf6" },
      { name: "CSS", percentage: 0.1, color: "#6366f1" },
      { name: "HTML", percentage: 0.1, color: "#f97316" },
    ],
    architectureSummary: "ESP32-S3 nodes process sensor inputs (MAX30102 pulse-ox, load-cell bed pressure, ultrasonic IV fluid level) using FreeRTOS queues and forward encrypted payloads via MQTT TLS 1.3 to a local Raspberry Pi 5 broker. An Edge-AI vision inference unit detects fall events within 200ms without sending camera feeds off-premise.",
    featured: true,
    category: "HealthTech",
    hardwareBOM: [
      { item: "ESP32-S3-WROOM-1 Dev Module", quantity: 2, status: "ISSUED" },
      { item: "MAX30102 Pulse Oximeter & Heart Rate", quantity: 2, status: "ALLOCATED" },
      { item: "DS18B20 Waterproof Temp Probe", quantity: 2, status: "ALLOCATED" },
      { item: "HX711 Bed Pressure Strain Gauge", quantity: 4, status: "ALLOCATED" },
      { item: "HC-SR04 Ultrasonic IV Drip Monitor", quantity: 2, status: "ISSUED" },
      { item: "Raspberry Pi 5 (8GB) Local Edge Gateway", quantity: 1, status: "RESERVED" },
    ],
    tasks: [
      { id: "tsk-01", projectId: "prj-001", title: "Implement FreeRTOS queue for SpO2 peak calculation", description: "Prevent sensor buffer overflows during high-frequency pulse sampling.", assignee: "HARI DHARANESH S P", priority: "HIGH", status: "COMPLETED", dueDate: "2026-09-10" },
      { id: "tsk-02", projectId: "prj-001", title: "Design 3D printable enclosure for patient bedside unit", description: "Design casing with cooling vents and OLED display cutout.", assignee: "BALAJI M M", priority: "MEDIUM", status: "IN_PROGRESS", dueDate: "2026-09-15" },
      { id: "tsk-03", projectId: "prj-001", title: "Stress-test Mosquitto broker with 10 simulated bedside nodes", description: "Measure packet loss and latency under high traffic.", assignee: "RASIA JAEL R", priority: "HIGH", status: "COMPLETED", dueDate: "2026-09-12" },
      { id: "tsk-04", projectId: "prj-001", title: "Set up battery low-voltage cutoff alert on OLED", description: "Notify nursing staff when LiPo drops below 3.4V.", assignee: "AKSHITHA B", priority: "MEDIUM", status: "TODO", dueDate: "2026-09-20" },
    ],
    reviews: [
      {
        id: "rev-r1-01",
        roundKey: "R1",
        roundTitle: "R1 First Review (Round 1) Evaluation",
        status: "PENDING",
        reviewerName: "Faculty Evaluator",
        reviewerRole: "TEACHER",
        evaluatedAt: "",
        feedback: "First Review has not been conducted yet. Feedback and action items will be updated here live once evaluated.",
        actionItems: [],
        rubricScores: [
          { criterion: "Problem Statement & Theme Relevance", score: 0, maxScore: 10 },
          { criterion: "Hardware BOM & Circuit Feasibility", score: 0, maxScore: 10 },
          { criterion: "Git Workflow & Commit Attribution", score: 0, maxScore: 10 },
          { criterion: "Edge-AI & Sensor Pipeline Architecture", score: 0, maxScore: 10 },
        ],
      },
      {
        id: "rev-r2-01",
        roundKey: "R2",
        roundTitle: "R2 Mid-Stage / Prototype Evaluation",
        status: "PENDING",
        reviewerName: "Faculty Evaluator",
        reviewerRole: "TEACHER",
        feedback: "Mid-stage prototype demonstration scheduled following Round 1 sign-off.",
        actionItems: [],
      },
      {
        id: "rev-final-01",
        roundKey: "FINAL",
        roundTitle: "Final Evaluations",
        status: "PENDING",
        reviewerName: "Hackathon Jury Panel",
        reviewerRole: "JUDGE",
        feedback: "Final evaluation rubric opens during Demo Day judging.",
        actionItems: [],
      },
    ],
    submissionFiles: [
      { id: "f-01", title: "CareGrid Hackathon Presentation Deck", fileName: "CareGrid_Pitch_Deck_v2.pptx", fileType: "PPTX", size: "14.2 MB", uploadedAt: "2026-09-14 14:30", downloadUrl: "#" },
      { id: "f-02", title: "System Architecture & Clinical Safety Whitepaper", fileName: "CareGrid_System_Whitepaper.pdf", fileType: "PDF", size: "3.8 MB", uploadedAt: "2026-09-14 15:10", downloadUrl: "#" },
      { id: "f-03", title: "Complete Hardware Bill of Materials & Cost Breakdown", fileName: "CareGrid_Hardware_BOM.xlsx", fileType: "XLSX", size: "620 KB", uploadedAt: "2026-09-14 16:05", downloadUrl: "#" },
      { id: "f-04", title: "Patient Monitoring & Nurse Alert Video Walkthrough", fileName: "CareGrid_Bedside_Demo.mp4", fileType: "MP4", size: "48.5 MB", uploadedAt: "2026-09-14 16:45", downloadUrl: "#" },
    ],
    resourceLinks: [
      { id: "l-01", title: "Firmware Repository (ESP32-S3 FreeRTOS)", url: "https://github.com/haridharanesh-official/CareGrid", category: "FIRMWARE", description: "C++ FreeRTOS tasks for sensor sampling, FreeRTOS queue buffering, and TLS MQTT client." },
      { id: "l-02", title: "PCB Gerber Files & KiCad Schematics", url: "https://github.com/haridharanesh-official/CareGrid/tree/main/hardware", category: "HARDWARE_PCB", description: "Custom 2-layer PCB layout with reverse-polarity protection and AMS1117 3.3V regulation." },
      { id: "l-03", title: "Bedside Unit 3D CAD Enclosure (STL)", url: "https://github.com/haridharanesh-official/CareGrid/tree/main/cad", category: "CAD_DESIGN", description: "PETG filament enclosure design with wall-mount bracket and sensor cord strain relief." },
      { id: "l-04", title: "Edge-AI Fall Detection ONNX Model", url: "https://github.com/haridharanesh-official/CareGrid/tree/main/models", category: "AI_MODEL", description: "Quantized MobileNetV3 model running at 28 FPS on Raspberry Pi 5." },
      { id: "l-05", title: "Live Clinical Ward Telemetry Stream", url: "/lab/live", category: "LIVE_DASHBOARD", description: "Real-time websocket feed of heart rate, SpO2, bed occupancy, and alert states." },
    ],
  },
  {
    id: "prj-002",
    title: "Autonomous Inspection Rover",
    tagline: "Industrial Hazard & Pipeline Inspection Robot",
    description: "A 4-wheel drive skid-steer rover equipped with thermal imaging, gas sensors (MQ-4, MQ-7), LiDAR obstacle avoidance, and ROS 2 navigation for inspecting hazardous industrial environments.",
    lifecycle: "DEVELOPMENT",
    leadName: "Rahul Menon",
    leadId: "std-002",
    members: [
      { name: "Rahul Menon", role: "Robotics Lead & ROS Developer" },
      { name: "Deepak S", role: "Motor Control & Power Electronics" },
      { name: "Swathi P", role: "Computer Vision & Object Avoidance" },
    ],
    facultyMentor: "Faculty Mentor",
    techStack: ["ROS 2", "Raspberry Pi 4", "Arduino Mega", "YOLOv8", "LiDAR", "Thermal Cam"],
    progressPercent: 64,
    githubUrl: "https://github.com/iot-club-org/inspection-rover",
    architectureSummary: "Arduino Mega handles low-level PID motor encoder controls via serial communication. Raspberry Pi runs ROS 2 Humble nodes for SLAM mapping and object detection.",
    featured: true,
    category: "Robotics",
    hardwareBOM: [
      { item: "RPLiDAR A1M8", quantity: 1, status: "ISSUED" },
      { item: "Cytron MDD10A Motor Driver", quantity: 2, status: "ISSUED" },
      { item: "High-Torque Planetary DC Motors", quantity: 4, status: "ALLOCATED" },
    ],
    tasks: [],
  },
  {
    id: "prj-003",
    title: "AgriSense LoRa Mesh",
    tagline: "Long-Range Soil & Microclimate Wireless Sensor Network",
    description: "Low-power battery-operated sensor nodes measuring soil moisture at dual depths, ambient temperature, humidity, and solar radiation, broadcasting over 3+ km using LoRa 868MHz mesh protocol to a solar-powered gateway.",
    lifecycle: "TESTING",
    leadName: "Kavya Swaminathan",
    leadId: "std-003",
    members: [
      { name: "Kavya Swaminathan", role: "RF & Embedded Lead" },
      { name: "Pranav M", role: "Hardware Power Optimization" },
    ],
    facultyMentor: "Faculty Mentor",
    techStack: ["ESP32-C3", "SX1276 LoRa", "Deep Sleep (15uA)", "Grafana"],
    progressPercent: 75,
    githubUrl: "https://github.com/iot-club-org/agrisense-lora-mesh",
    architectureSummary: "Ultra-low-power ESP32-C3 modules wake every 15 minutes, sample capacitive soil sensors, transmit encrypted LoRa packets, and return to deep sleep.",
    featured: false,
    category: "AgriTech",
    hardwareBOM: [],
    tasks: [],
  },
];

export const initialHardwareAssets: HardwareAsset[] = [
  {
    assetId: "ESP024",
    name: "ESP32-S3 DevKitC-1 N16R8",
    category: "Microcontroller",
    model: "ESP32-S3-WROOM-1",
    serialNumber: "SN-ESP-2024-0024",
    location: "IoT Lab Shelf B2",
    condition: "GOOD",
    status: "ISSUED",
    currentHolder: "Hari Dharanesh SP",
    currentHolderId: "std-001",
    projectAllocation: "CareGrid",
    issuedDate: "2026-09-08",
    expectedReturnDate: "2026-09-22",
    qrCodeValue: "https://iotclub.org/lab/assets/ESP024",
    specs: ["Xtensa dual-core 32-bit LX7 @ 240 MHz", "16MB Flash, 8MB Octal PSRAM", "Wi-Fi 802.11 b/g/n & BLE 5.0", "45 Programmable GPIOs"],
  },
  {
    assetId: "ESP025",
    name: "ESP32 DevKit V1",
    category: "Microcontroller",
    model: "ESP-WROOM-32",
    serialNumber: "SN-ESP-2024-0025",
    location: "IoT Lab Shelf B2",
    condition: "GOOD",
    status: "AVAILABLE",
    qrCodeValue: "https://iotclub.org/lab/assets/ESP025",
    specs: ["Dual-Core 240MHz", "4MB Flash", "Wi-Fi & Bluetooth Classic/BLE", "30-pin DIP layout"],
  },
  {
    assetId: "RPI005",
    name: "Raspberry Pi 5 8GB RAM",
    category: "Single Board Computer",
    model: "Raspberry Pi 5 Model B",
    serialNumber: "SN-RPI-2024-0005",
    location: "IoT Lab Secure Cabinet A1",
    condition: "EXCELLENT",
    status: "AVAILABLE",
    qrCodeValue: "https://iotclub.org/lab/assets/RPI005",
    specs: ["Broadcom BCM2712 quad-core Arm Cortex-A76 @ 2.4GHz", "8GB LPDDR4X SDRAM", "PCIe 2.0 interface", "Dual 4Kp60 micro-HDMI"],
  },
  {
    assetId: "LRA008",
    name: "LoRa SX1278 433MHz Transceiver Module",
    category: "Wireless & RF",
    model: "Ra-02 AI-Thinker",
    serialNumber: "SN-LRA-2023-0008",
    location: "IoT Lab Drawer C3",
    condition: "GOOD",
    status: "AVAILABLE",
    qrCodeValue: "https://iotclub.org/lab/assets/LRA008",
    specs: ["+20dBm output power", "High sensitivity down to -148dBm", "SPI Interface", "Range up to 5-10 km"],
  },
  {
    assetId: "OSC002",
    name: "Rigol DS1054Z 50MHz Digital Oscilloscope",
    category: "Testing Equipment",
    model: "DS1054Z 4-Channel",
    serialNumber: "SN-RIG-2022-0002",
    location: "Testing Bench Station 2",
    condition: "EXCELLENT",
    status: "AVAILABLE",
    qrCodeValue: "https://iotclub.org/lab/assets/OSC002",
    specs: ["4 Channels, 50MHz Bandwidth (upgradable)", "1 GSa/s real-time sample rate", "24 Mpts memory depth", "Serial decode (I2C, SPI, UART)"],
  },
  {
    assetId: "SLD004",
    name: "Hakko FX-888D Digital Soldering Station",
    category: "Tooling",
    model: "FX-888D 70W",
    serialNumber: "SN-HAK-2023-0004",
    location: "Soldering Station Bench 1",
    condition: "GOOD",
    status: "AVAILABLE",
    qrCodeValue: "https://iotclub.org/lab/assets/SLD004",
    specs: ["70W Heating Element", "Adjustable temp 50°C - 480°C", "ESD safe ceramic heater", "Digital calibration"],
  },
  {
    assetId: "SNS012",
    name: "BH1750 Ambient Light Sensor Module",
    category: "Sensor",
    model: "GY-302 BH1750FVI",
    serialNumber: "SN-SNS-2024-0012",
    location: "IoT Lab Drawer D1",
    condition: "GOOD",
    status: "ISSUED",
    currentHolder: "Hari Dharanesh SP",
    currentHolderId: "std-001",
    projectAllocation: "CareGrid",
    qrCodeValue: "https://iotclub.org/lab/assets/SNS012",
    specs: ["I2C Interface (Address 0x23 or 0x5C)", "1 - 65535 lx range", "Direct lux reading without conversion", "3.3V / 5V compatible"],
  },
  {
    assetId: "SEN019",
    name: "PMS5003 Laser Particle Concentration Sensor",
    category: "Sensor",
    model: "Plantower PMS5003",
    serialNumber: "SN-SEN-2023-0019",
    location: "IoT Lab Drawer D2",
    condition: "GOOD",
    status: "UNDER_TESTING",
    qrCodeValue: "https://iotclub.org/lab/assets/SEN019",
    specs: ["Measures PM1.0, PM2.5, PM10", "Laser scattering principle", "UART Digital Output", "Zero false-alarm rate"],
  },
];

export const initialHardwareRequests = [
  {
    id: "req-01",
    assetId: "ESP025",
    assetName: "ESP32 DevKit V1",
    studentId: "std-004",
    studentName: "Sneha Reddy",
    project: "Secure MQTT Gateway",
    purpose: "Testing TLS certificates and secure boot loading.",
    durationDays: 14,
    requestedAt: "2026-09-11",
    status: "PENDING" as const,
  },
  {
    id: "req-02",
    assetId: "LRA008",
    assetName: "LoRa SX1278 433MHz Transceiver Module",
    studentId: "std-003",
    studentName: "Kavya Swaminathan",
    project: "AgriSense LoRa Mesh",
    purpose: "Field range testing at agricultural plots.",
    durationDays: 21,
    requestedAt: "2026-09-10",
    status: "PENDING" as const,
  },
];

export const initialLabResources: LabResource[] = [
  {
    id: "res-01",
    name: "Soldering & Desoldering Station #1",
    category: "Fabrication",
    capacity: 2,
    description: "Equipped with Hakko FX-888D digital iron, fume extractor, hot air rework station, microscope, and flux cleaning gear.",
    isAvailable: true,
    equipment: ["Hakko FX-888D", "Quick 861DW Hot Air", "AmScope Stereo Microscope", "Kester 63/37 Solder Wire"],
  },
  {
    id: "res-02",
    name: "Rigol Digital Oscilloscope Station",
    category: "Testing",
    capacity: 2,
    description: "4-channel 50MHz oscilloscope with logic analyzer probes, arbitrary function generator, and programmable DC power supply.",
    isAvailable: true,
    equipment: ["Rigol DS1054Z", "Rigol DG1022Z Function Gen", "Korad 30V 5A Linear Bench Supply"],
  },
  {
    id: "res-03",
    name: "Creality K1 Max High-Speed 3D Printer",
    category: "Fabrication",
    capacity: 1,
    description: "Enclosed core-XY printer for rapid prototyping of sensor enclosures, robotics chassis, and brackets in PLA/PETG/ABS.",
    isAvailable: true,
    equipment: ["Creality K1 Max (300x300x300mm)", "0.4mm Hardened Nozzle", "Sunlu Filament Dryer Box"],
  },
  {
    id: "res-04",
    name: "Robotics Prototyping Workbench",
    category: "Workbench",
    capacity: 4,
    description: "Heavy-duty antistatic bench with overhead DC supplies, motor test dyno, tachometers, and LiPo charging safety station.",
    isAvailable: true,
    equipment: ["Antistatic ESD Mat", "ISDT Dual LiPo Balance Charger", "Optical Tachometer", "Tool chest"],
  },
  {
    id: "res-05",
    name: "Embedded Computing & Gateway Bench",
    category: "Computing",
    capacity: 3,
    description: "Dedicated bench with dual-monitor Linux workstations, logic analyzers, UART-USB adapters, and wired Gigabit PoE switches.",
    isAvailable: true,
    equipment: ["Ubuntu 24.04 LTS Workstation", "Saleae 8-Ch Logic Analyzer", "FTDI Breakout Boards"],
  },
];

export const initialLabBookings: LabBooking[] = [
  {
    id: "bk-001",
    resourceId: "res-04",
    resourceName: "Robotics Prototyping Workbench",
    userId: "std-001",
    userName: "Hari Dharanesh SP",
    project: "CareGrid Enclosure Assembly",
    date: "2026-09-12",
    startTime: "16:00",
    endTime: "18:00",
    status: "CONFIRMED",
  },
  {
    id: "bk-002",
    resourceId: "res-03",
    resourceName: "Creality K1 Max High-Speed 3D Printer",
    userId: "std-002",
    userName: "Rahul Menon",
    project: "Autonomous Rover Sensor Mounts",
    date: "2026-09-13",
    startTime: "10:00",
    endTime: "13:00",
    status: "CONFIRMED",
  },
];

export const initialClubEvents: ClubEvent[] = [
  {
    id: "evt-01",
    title: "ESP32 + MQTT Firmware Bootcamp",
    type: "Bootcamp",
    description: "A comprehensive 6-hour intensive bootcamp covering Wi-Fi stack initialization, Mosquitto broker setup, JSON telemetry serialization, and Last Will Testament.",
    trainer: "Faculty Mentor / Club Technical Lead",
    venue: "IoT Center of Excellence, Lab 304",
    date: "2026-09-19",
    startTime: "10:00",
    endTime: "16:00",
    capacity: 50,
    registeredCount: 42,
    prerequisites: ["IoT Foundations Track", "Basic C++ Programming"],
    isRegistered: true,
    attendanceToken: "IOT-SEC-9842",
    tokenExpiresAt: "2026-09-19T10:15:00",
  },
  {
    id: "evt-02",
    title: "FreeRTOS Kernel & Real-Time Task Scheduling",
    type: "Workshop",
    description: "Master concurrent task handling, thread-safe queues, and priority inversion resolution on dual-core microcontrollers.",
    trainer: "Senior Embedded Engineer",
    venue: "Seminar Hall B & Lab Station",
    date: "2026-09-26",
    startTime: "14:00",
    endTime: "17:30",
    capacity: 40,
    registeredCount: 28,
    prerequisites: ["ESP32 Basics", "Pointers in C"],
    isRegistered: false,
  },
  {
    id: "evt-03",
    title: "Edge AI with Raspberry Pi & YOLO Object Detection",
    type: "Workshop",
    description: "Deploy quantized convolutional neural networks onto edge gateways for real-time camera inference and safety monitoring.",
    trainer: "AIoT Research Mentor",
    venue: "IoT Lab 304",
    date: "2026-10-03",
    startTime: "10:30",
    endTime: "15:00",
    capacity: 35,
    registeredCount: 31,
    prerequisites: ["Python Fundamentals", "Linux Shell"],
    isRegistered: false,
  },
];

export const initialHackathons: HackathonOpportunity[] = [
  {
    id: "opp-01",
    title: "Smart India Hackathon (SIH) 2026",
    organizer: "Ministry of Education & AICTE",
    category: "Hackathons",
    deadline: "2026-09-30",
    prizePool: "₹1,00,000 per Problem Statement",
    mode: "Hybrid",
    teamStatus: "FINALIST",
    teamName: "Team CareGrid",
    teamMembers: ["Hari Dharanesh SP", "Divya Balaji", "Manoj Kumar", "Siddharth Verma", "Ananya Iyer", "Tarun Prasad"],
    description: "National premier innovation hackathon. Selected under Smart Healthcare Domain (Problem Statement: Low-cost wireless patient vitals grid).",
  },
  {
    id: "opp-02",
    title: "IEEE International IoT & Edge Computing Challenge",
    organizer: "IEEE IoT Technical Community",
    category: "IoT Competitions",
    deadline: "2026-10-15",
    prizePool: "$5,000 USD",
    mode: "Online",
    teamStatus: "REGISTERED",
    teamName: "RoboInspect Core",
    teamMembers: ["Rahul Menon", "Deepak S", "Swathi P"],
    description: "Global challenge for autonomous edge robotics operating under zero or intermittent cloud connectivity.",
  },
  {
    id: "opp-03",
    title: "National Robotics Championship 2026",
    organizer: "RoboIndia Federation",
    category: "Robotics",
    deadline: "2026-11-05",
    prizePool: "₹75,000",
    mode: "In-Person",
    teamStatus: "LOOKING_FOR_TEAM",
    description: "Arena challenge for autonomous navigation through obstacle fields with payload delivery.",
  },
];

export const initialCertificates: CertificateRecord[] = [
  {
    certificateId: "IOT-2026-ESP32-0042",
    studentName: "Hari Dharanesh SP",
    studentRoll: "22IOT042",
    trackOrTopic: "ESP32 Embedded Systems & Real-Time Firmware",
    level: "Level II – Practical Mastery",
    issueDate: "2026-09-02",
    issuerTitle: "Faculty Mentor / Club Technical Board",
    qrUrl: "https://iotclub.org/verify/IOT-2026-ESP32-0042",
    isValid: true,
    gradeOrScore: "94/100 (Distinction)",
  },
  {
    certificateId: "IOT-2026-NET-0019",
    studentName: "Hari Dharanesh SP",
    studentRoll: "22IOT042",
    trackOrTopic: "IoT Networking & MQTT Architecture",
    level: "Level I – Foundations",
    issueDate: "2026-08-25",
    issuerTitle: "Faculty Mentor / Club Technical Board",
    qrUrl: "https://iotclub.org/verify/IOT-2026-NET-0019",
    isValid: true,
    gradeOrScore: "96/100 (Distinction)",
  },
];

export const initialMonthlyChallenges: MonthlyChallenge[] = [
  {
    id: "ch-09-2026",
    month: "September 2026",
    title: "Smart Energy Monitoring Challenge",
    tagline: "Build a non-invasive current monitoring node with MQTT telemetry",
    difficulty: "Intermediate",
    requirements: [
      "ESP32 or ESP8266 microcontroller",
      "SCT-013-000 non-invasive AC current sensor or ACS712",
      "MQTT publish topic: iotclub/challenge/energy/{team_id}",
      "Web or mobile telemetry dashboard with instantaneous wattage & kWh calculation",
      "Working GitHub repository with schematic and README",
    ],
    xpReward: 500,
    badgeReward: "Energy IoT Specialist",
    deadline: "2026-09-30",
    participantsCount: 24,
    isRegistered: true,
  },
];

export const initialTeamRecruitments: TeamRecruitmentPost[] = [
  {
    id: "tm-01",
    projectId: "prj-002",
    projectTitle: "Autonomous Inspection Rover",
    leadName: "Rahul Menon",
    openRoles: ["Computer Vision Developer (OpenCV / YOLO)", "ROS 2 Navigation Specialist", "CAD & 3D Printing Designer"],
    description: "Looking for dedicated club members to finalize our LiDAR mapping and obstacle avoidance pipelines for IEEE competition.",
    applicantsCount: 4,
    createdAt: "2026-09-06",
  },
  {
    id: "tm-02",
    projectId: "prj-003",
    projectTitle: "AgriSense LoRa Mesh",
    leadName: "Kavya Swaminathan",
    openRoles: ["Low-Power Firmware Engineer (C/C++)", "Frontend Dashboard Developer (Next.js/Grafana)"],
    description: "Developing extreme low-power sensor nodes that run 12+ months on 18650 Li-ion cells.",
    applicantsCount: 2,
    createdAt: "2026-09-09",
  },
];

export const initialTelemetry: TelemetryData = {
  temperatureC: 28.2,
  humidityPercent: 62,
  airQualityAqi: 38,
  powerConsumptionKw: 1.84,
  occupancyCount: 17,
  nodesOnline: 11,
  nodesTotal: 12,
  benchesActive: 4,
  benchesTotal: 6,
  lastUpdated: new Date().toISOString(),
  deviceHistory: [
    { time: "14:00", temp: 27.8, power: 1.45 },
    { time: "14:15", temp: 28.0, power: 1.62 },
    { time: "14:30", temp: 28.1, power: 1.78 },
    { time: "14:45", temp: 28.4, power: 1.85 },
    { time: "15:00", temp: 28.2, power: 1.84 },
  ],
};

export const initialAuditLogs: AuditLogItem[] = [
  { id: "log-01", user: "Faculty Mentor", action: "EVALUATION_COMPLETED", entity: "AssignmentSubmission", entityId: "asg-201", timestamp: "2026-09-12 14:10", details: "Awarded 94/100 to Hari Dharanesh SP for ESP32 FreeRTOS Practical." },
  { id: "log-02", user: "Lab Admin", action: "HARDWARE_ISSUED", entity: "HardwareAsset", entityId: "ESP024", timestamp: "2026-09-08 11:30", details: "Issued ESP32-S3 #ESP024 to Hari Dharanesh SP for CareGrid." },
  { id: "log-03", user: "Club Admin", action: "RECRUITMENT_STAGE_CHANGED", entity: "Application", entityId: "APP-2026-001", timestamp: "2026-09-08 16:45", details: "Promoted Aravind Kumar to ASSESSMENT stage." },
  { id: "log-04", user: "Faculty Mentor", action: "CERTIFICATE_ISSUED", entity: "CertificateRecord", entityId: "IOT-2026-ESP32-0042", timestamp: "2026-09-02 09:15", details: "Issued ESP32 Level II certificate to Hari Dharanesh SP." },
  { id: "log-05", user: "Lab Admin", action: "LAB_BOOKING_CONFIRMED", entity: "LabBooking", entityId: "bk-001", timestamp: "2026-09-12 10:00", details: "Confirmed Robotics Workbench for CareGrid team (16:00 - 18:00)." },
];

export const initialNotifications: AppNotification[] = [
  { id: "notif-01", title: "Assignment Evaluation", message: "Your ESP32 FreeRTOS Practical was evaluated: 94/100 (+100 XP)", type: "ASSIGNMENT", timestamp: "10 mins ago", read: false },
  { id: "notif-02", title: "Hardware Return Reminder", message: "ESP32-S3 #ESP024 is due in 10 days (22 Sep 2026).", type: "HARDWARE", timestamp: "2 hours ago", read: false },
  { id: "notif-03", title: "Workshop Confirmed", message: "You are registered for ESP32 + MQTT Firmware Bootcamp on Saturday.", type: "WORKSHOP", timestamp: "1 day ago", read: true },
  { id: "notif-04", title: "Lab Reservation", message: "Robotics Prototyping Workbench is booked for today 4:00 PM - 6:00 PM.", type: "LAB", timestamp: "3 hours ago", read: false },
];
